import { useEffect, useState } from "react";
import { useAuth } from "@/hooks/useAuth";
import { supabase } from "@/integrations/supabase/client";
import { DashboardLayout } from "@/components/layout/DashboardLayout";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { Shield, Filter } from "lucide-react";

interface Lead {
  id: string;
  name: string;
  college_name: string | null;
  branch: string | null;
  year: string | null;
  semester: string | null;
  phone: string | null;
  email: string | null;
  course_interested: string | null;
  lead_type: string;
  status: string;
  assigned_bde_id: string | null;
  created_by: string;
}

interface BdeProfile {
  user_id: string;
  full_name: string;
}

const statusLabels: Record<string, string> = {
  initial_contact: "Initial Contact",
  whatsapp_group_created: "WhatsApp Group",
  re_initiate_call: "Re-Initiate Call",
  converted: "Converted",
  paid: "Paid",
  not_interested: "Not Interested",
};

export default function AdminLeadsGenerated() {
  const { role } = useAuth();
  const [leads, setLeads] = useState<Lead[]>([]);
  const [bdeProfiles, setBdeProfiles] = useState<BdeProfile[]>([]);
  const [loading, setLoading] = useState(true);
  const [branchFilter, setBranchFilter] = useState("");
  const [collegeFilter, setCollegeFilter] = useState("");
  const [yearFilter, setYearFilter] = useState("all");
  const [bdeFilter, setBdeFilter] = useState("all");

  useEffect(() => {
    const fetchData = async () => {
      const { data: leadsData } = await supabase.from("leads").select("*").order("created_at", { ascending: false });
      setLeads((leadsData || []) as Lead[]);

      const { data: bdeRoles } = await supabase.from("user_roles").select("user_id").eq("role", "bde");
      if (bdeRoles && bdeRoles.length > 0) {
        const ids = bdeRoles.map(r => r.user_id);
        const { data: profiles } = await supabase.from("profiles").select("id, full_name").in("id", ids);
        setBdeProfiles((profiles || []).map(p => ({ user_id: p.id, full_name: p.full_name })));
      }
      setLoading(false);
    };
    fetchData();
  }, []);

  if (role !== "admin") {
    return <DashboardLayout><div className="flex flex-col items-center justify-center py-12"><Shield className="mb-4 h-12 w-12 text-muted-foreground" /><h3>Access Denied</h3></div></DashboardLayout>;
  }

  const filtered = leads.filter(l => {
    if (branchFilter && !l.branch?.toLowerCase().includes(branchFilter.toLowerCase())) return false;
    if (collegeFilter && !l.college_name?.toLowerCase().includes(collegeFilter.toLowerCase())) return false;
    if (yearFilter !== "all" && l.year !== yearFilter) return false;
    if (bdeFilter !== "all" && l.created_by !== bdeFilter) return false;
    return true;
  });

  const getBdeName = (id: string | null) => {
    if (!id) return "-";
    return bdeProfiles.find(b => b.user_id === id)?.full_name || "-";
  };

  return (
    <DashboardLayout>
      <div className="space-y-6">
        <div className="fade-in">
          <h1 className="text-2xl font-bold md:text-3xl">Leads Generated (Monitor)</h1>
          <p className="text-muted-foreground">Monitor leads generated by BDE team members.</p>
        </div>

        <Card className="slide-up">
          <CardHeader className="pb-3">
            <CardTitle className="flex items-center gap-2 text-base"><Filter className="h-4 w-4" /> Filters</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
              <div className="space-y-2"><Label>College</Label><Input placeholder="Filter..." value={collegeFilter} onChange={e => setCollegeFilter(e.target.value)} /></div>
              <div className="space-y-2"><Label>Branch</Label><Input placeholder="Filter..." value={branchFilter} onChange={e => setBranchFilter(e.target.value)} /></div>
              <div className="space-y-2">
                <Label>Year</Label>
                <Select value={yearFilter} onValueChange={setYearFilter}>
                  <SelectTrigger><SelectValue /></SelectTrigger>
                  <SelectContent>
                    <SelectItem value="all">All</SelectItem>
                    {[1,2,3,4].map(y => <SelectItem key={y} value={String(y)}>{y}</SelectItem>)}
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-2">
                <Label>BDE</Label>
                <Select value={bdeFilter} onValueChange={setBdeFilter}>
                  <SelectTrigger><SelectValue /></SelectTrigger>
                  <SelectContent>
                    <SelectItem value="all">All BDEs</SelectItem>
                    {bdeProfiles.map(b => <SelectItem key={b.user_id} value={b.user_id}>{b.full_name}</SelectItem>)}
                  </SelectContent>
                </Select>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader><CardTitle>Leads ({filtered.length})</CardTitle></CardHeader>
          <CardContent>
            <div className="overflow-x-auto">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Name</TableHead>
                    <TableHead>College</TableHead>
                    <TableHead>Branch</TableHead>
                    <TableHead>Year</TableHead>
                    <TableHead>Status</TableHead>
                    <TableHead>Generated By (BDE)</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {filtered.length === 0 ? (
                    <TableRow><TableCell colSpan={6} className="text-center py-8 text-muted-foreground">No leads found</TableCell></TableRow>
                  ) : (
                    filtered.map(lead => (
                      <TableRow key={lead.id}>
                        <TableCell className="font-medium">{lead.name}</TableCell>
                        <TableCell>{lead.college_name || "-"}</TableCell>
                        <TableCell>{lead.branch || "-"}</TableCell>
                        <TableCell>{lead.year || "-"}</TableCell>
                        <TableCell><Badge variant="outline">{statusLabels[lead.status] || lead.status}</Badge></TableCell>
                        <TableCell>{getBdeName(lead.created_by)}</TableCell>
                      </TableRow>
                    ))
                  )}
                </TableBody>
              </Table>
            </div>
          </CardContent>
        </Card>
      </div>
    </DashboardLayout>
  );
}
